### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by tommypolly**
in server setting when you write something is a bit illegible :)
and i have corrected the buttons: connect, edit and delete

### CODE REVIEW

**Comment by kooohei** [comment]
oops, sorry i revert this commit.
because it consistency is gone to the buttons.
only me?

**Comment by tommypolly** [comment]
I do not know what the problem is but to me when I updated the file style.css buttons no longer worked and I had to cancel my ftp, re-connect and after everything worked o.O"

**Comment by kooohei** [comment]
button_diff

no problem for function.
just lookin.

**Comment by tommypolly** [comment]
I have to redo the pull request?
I'm new on github :)

**Comment by kooohei** [comment]
yea sure!

**Pull request merged**
