### PR TITLE
Added a troubleshooting section

### PR DESCRIPTION
**Pull request by ManojAMK**
I was facing some issues with a server having enormous amount of files. Added some guidelines on how to fix it.

### CODE REVIEW

**Comment by kooohei** [comment]
thx your pull request.

**Comment by kooohei** [comment]
added user can specified exclude files to server setting panel.

**Comment by ManojAMK** [comment]
Thanks buddy! :) I was wishing for NppFTP plugin, but for Brackets. Your plugin works almost the same. But when I am saving the changes, the changes are not applied on the server files. Is this a bug or the extension doesn't work that way?

**Comment by kooohei** [comment]
ok, did your account has valid permission to the file?

**Comment by kooohei** [comment]
you can check error log when the file could not saved.
debug > Show Developer Tools
plz tell me a error message, in the console tab on developer tools, if you can. ;)

**Comment by ManojAMK** [comment]
Yes, I use the server owner's/root user's account. I can edit the file using NppFTP, but not from Synapse. 

BTW I cannot update the extension(I can update all other extensions):

updatefailed

**Comment by kooohei** [comment]
ok thx for reply, the extension remove from brackets.
you can reinstall from brackets extension manager.

**Comment by kooohei** [comment]
and now, Synapse current version is 1.0.7. your screen shots ishow my extension ver 1.0.5.
plz reload extension manager.

**Pull request merged**
